name: Rust workflow
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "setup"
  lint:
    runs-on: ubuntu-latest
    container: rust:alpine3.20
    steps: 
      - run: cargo clippy
  test:
    runs-on: ubuntu-latest
    container: rust:alpine3.20
    needs: lint
    steps:
      - run: echo "test"
  dependency_scanning:
    runs-on: ubuntu-latest
    container: rust:alpine3.20
    needs: lint
    steps:
      - run: echo "dependency scanning"  
  build:
    runs-on: ubuntu-latest
    container: rust:alpine3.20
    needs: lint
    steps:
      - run: echo "build"
  sbomb:
    runs-on: ubuntu-latest
    container: rust:alpine3.20
    needs: build
    steps:
      - run: echo "sbomb"
  semantic_release:
    if: ${{github.event}} == "pull_request"
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - run: echo "semantic release"
